module.exports = Object.freeze({
    ERR_001: { errorCode: 'E001', errorMessage: 'User creation failed.'},
    ERR_002: { errorCode: 'E002', errorMessage: 'User not found.'},
    ERR_003: { errorCode: 'E003', errorMessage: 'Error fetching all users.'},
    ERR_004: { errorCode: 'E004', errorMessage: 'Error fetching user by id.'},
    ERR_005: { errorCode: 'E005', errorMessage: 'Error updating user details.'},
    ERR_006: { errorCode: 'E006', errorMessage: 'Error deleting user.'},
    ERR_007: { errorCode: 'E007', errorMessage: 'Error deleting old non ready user records.'},
    ERR_008: { errorCode: 'E008', errorMessage: 'Error while creating auth record.'},
    ERR_009: { errorCode: 'E009', errorMessage: 'Error while sync update.'},
    ERR_010: { errorCode: 'E010', errorMessage: 'Error while sync finish.'},
    ERR_011: { errorCode: 'E011', errorMessage: 'Error while restore initialization.'},
    ERR_012: { errorCode: 'E012', errorMessage: 'Error while validating password.'},
    ERR_013: { errorCode: 'E013', errorMessage: 'Username or password does not match.'},
});